CREATE TABLE Assorted(
	assortedId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	userId INT NOT NULL,
	itemName VARCHAR(300)
);

CREATE TABLE Category(
	categoryId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	userId INT NOT NULL,
	name VARCHAR(300)
);

CREATE TABLE Recipe(
	recipeId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	userId INT NOT NULL,
	name VARCHAR(300),
	ingredients TEXT,
	categoryId INT,
	categoryName VARCHAR(300)
);

CREATE TABLE User_(
	userId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	emailAddress VARCHAR(300),
	password VARCHAR(300)
);